export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_UP_POST = 'VOTE_UP_POST';
export const VOTE_DOWN_POST = 'VOTE_DOWN_POST';
export const SORT_POSTS_BY = 'SORT_POSTS_BY';

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_SINGLE_COMMENT = 'GET_SINGLE_COMMENT';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const VOTE_UP_COMMENT = 'VOTE_UP_COMMENT';
export const VOTE_DOWN_COMMENT = 'VOTE_DOWN_COMMENT';
